name: "Todoist Voice HA"
description: "Simple test"
version: "1.0.0"
slug: "todoist-voice-ha"
arch:
  - amd64
startup: application
boot: manual
ports:
  8080/tcp: 8080
options: {}
schema: {}
image: "alpine:latest"
