name: Build Add-on

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.PACKAGES_TOKEN }}" | docker login ghcr.io -u f00lycooly --password-stdin
      
      - name: Build Docker image
        run: |
          cd todoist-voice-ha
          docker build -t ghcr.io/f00lycooly/todoist-voice-ha:latest .
      
      - name: Push Docker image
        run: docker push ghcr.io/f00lycooly/todoist-voice-ha:latest
