name: Build Add-on

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build Docker image
        run: |
          cd todoist-voice-ha
          # Use the full repository path
          docker build -t ghcr.io/${{ github.repository_owner }}/todoist-voice-ha:latest .
      
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/todoist-voice-ha:latest
