name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: addon/package-lock.json
      
      - name: Install dependencies
        run: cd addon && npm ci
      
      - name: Run tests
        run: cd addon && npm test
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Test integration
        run: |
          python -m py_compile custom_components/todoist_voice_ha_integration/*.py
