name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'addon/package-lock.json'
        # Only cache if lock file exists
        if: hashFiles('addon/package-lock.json') != ''
      
      - name: Install dependencies
        run: |
          cd addon
          npm ci || npm install
      
      - name: Run tests (if test script exists)
        run: |
          cd addon
          if npm run test > /dev/null 2>&1; then
            npm test
          else
            echo "No tests configured yet"
          fi
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Test integration (if files exist)
        run: |
          if find custom_components -name "*.py" | grep -q .; then
            python3 -m py_compile custom_components/todoist_voice_ha_integration/*.py
          else
            echo "No Python files to test yet"
          fi